---
title: "Access the Plumber Aggregation API"
output:
  html_document:
    df_print: paged
---

### Run this code on your local machine to pull data from the API 

##### Note API is hosted on your remote server - to start it up:
* cd r-plumber-aggreg
* docker build -t r-plumber-aggreg .
* docker run -p 8080:8000 r-plumber-aggreg


### Load Libraries

```{r}

library("httr2")
library("jsonlite")

# Read IP address from file for privacy
ipv4 <- scan("../ipv4.txt", what="character")

# read in input data file
employee_data <- fromJSON(txt="input/employee_data.json")

```

### POST request to the aggregate API

```{r}

# Initialize the API request
link <- paste0("http://",ipv4,":8080/employee-summary")

req <- request(link)

req <- req_body_json(req, list(employee_json=employee_data))
  
req_dry_run(req)

# Get result from API
resp <- req_perform(req)

# Check status of HTTP Call
resp_status(resp)

# Pull the body as list
msg <- resp_body_string(resp)
msg_list <- fromJSON(txt=msg)
msg_list



```




















